package model;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;


/**
 * This class represents a User
 */
public class User implements Serializable {

    private String userID; // Unique user ID generated by database
    private String password; // The password of this use
    private String firstName; // The first name of this user
    private String lastName; // The last name of this user
    private Date dateOfBirth; // The DOB of this user
    private String emailAddress; // The user's email address
    private String joinDate; // The user's join date
    private String lastActive; // The user's last active date
    private String gender; // The user's gender
    private String religion; // The user's current religion preference
    private String userType; // The user type
    private int age = 0; // The user age

    /**
     * Default Constructor
     */
    public User() {}

    public User(String userID, String firstName, String lastName, String emailAddress) {
        this.userID = userID;
        this.firstName = firstName;
        this.joinDate = Calendar.getInstance().getTime().toString();
    }

    /**
     * @return - The ID used to query for this User object from Firebase
     */
    public String getId() {
        return userID;
    }

    /**
     * @param userID - The ID used to query for this User object from Firebase
     */
    public void setId(String userID) {
        this.userID = userID;
    }

    /**
     * @return -  The user's first name
     */
    public String getFirstName() {
        return firstName;
    }

}

